[package]
name = "plant-thirst"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
futures = "0.3"
influxdb2 = "0.3"
influxdb2-derive = "0.1"
influxdb2-structmap = "0.2"
num-traits = "0.2"
tokio = { version = "1.21", features = ["full"] }
tokio-serial = "5.4"
